language: c++

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - build-essential
      - qt5-default
      - libqt5svg5-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --force qt ; fi
  - git clone https://github.com/neonsoftware/sndwch.git

script:

  - pwd 
  - cd sndwch/build
  - cmake ..
  - make
  - sudo make install
  - cd ../../
  - mkdir build
  - cd build
  - cmake ../src
  - make