language: c++

os:
  - linux
  - osx

sudo: required

env:
  - RELEASE_DIR=${TRAVIS_BUILD_DIR}/release/sndgui-${TRAVIS_OS_NAME}-${TRAVIS_TAG} RELEASE_ARCHIVE=${RELEASE_DIR}.tar.gz

addons:
  apt:
    packages:
      - build-essential
      - qt5-default
      - libqt5svg5-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --overwrite --force qt ; export PATH="/usr/local/opt/qt/bin:$PATH"; fi
  - git clone https://github.com/neonsoftware/sndwch.git
  - cd sndwch/build && cmake .. && cmake --build . --target install && cd ../../
  - env

script:
  - mkdir build && cd build && cmake ../src && cmake --build . && cd ..

before_deploy:
  - mkdir -p ${RELEASE_DIR}
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then macdeployqt build/sndgui.app -dmg ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then macdeployqt build/svgeditor.app -dmg ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp -v build/*.dmg ${RELEASE_DIR}; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp build/sndgui ${RELEASE_DIR} ; fi  
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cp build/svgeditor ${RELEASE_DIR} ; fi  
  - cd ${RELEASE_DIR}
  - tar -zcf ${RELEASE_ARCHIVE} *

deploy:
  provider: releases
  api_key:
    secure: R+6uHDsZC8nanUFl0PqGyshFYG4gRjlqiM6SgBzASmqkjtpIXh9+0/NdUee+PcEd2xNfRSK+m6ClISTgTDXiV8xoX3kFzzOVXvfTCCIewR1KjaPmmOg1xHzt7ioLf1DDIkPT+9STLFwtHYmYZlfR1DZrYyL7+PtlXv2QPsmtjYXit42ECVOJ7zzxVJyu2L1YsUUqvdcg0I3JuXVQfzquUK4ijYzgogOQrHkW6I+HLsVxdzPGzyzZB4NvGXeIOzvPw4peklrZAP+CRK5ig5WNhw4NMUjM8SvYWCXH318bC+htp1c3MyGUYWqsbjzIYNKSjk7r+svYhAk3eIpggzZ28p+obHNL9dnIWQKpW9P7cCPjSUbNZOTffUCvy7jJg3uKoHv53JSyOE8s4V9OB0sb6v45DfbZL3rY8tz6FmQ6ZG9xQM5wC4j2FOwwYglpbClI85d94PpigXnvLZUE9ZpN3IO2SMpy2YSIThegFHAF0LbREuSBE82Wwyum+S2R6J+8hQv0DeJuDLC8vbmsXhIOpnP/A9tXYzNuMY+jTtTNr+14foynw2UqemBy/YglE+kkB38EXv/H+74aU5ZLupv3Q3j0S6U8OSMWHoy2R5XDQdQxN8wN9qsSt9kHvO8bcj/ISsh22sl5vrIq1JweWS0dPia08y9wayODaldDWOlpCnQ=
  file: '${RELEASE_ARCHIVE}'
  skip_cleanup: true
  on:
    tags: true