language: c++
compiler: g++

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get update
  - git clone git@github.com:neonsoftware/sndwch.git
  - cd sndwch
  - mkdir build
  - cd build
  - cmake ../src
  - make
  - make install

install:
  - sudo apt-get install build-essential qt5-default
  - sudo apt-cache search qt

script:
  - mkdir build
  - cd build
  - cmake ../src
  - make