language: c++
compiler: g++

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
  - sudo apt-get update
  - git clone https://github.com/neonsoftware/sndwch.git

install:
  - sudo apt-get install build-essential qt5-default
  - sudo apt-cache search qt

script:

  - pwd 
  - mkdir -p $HOME/lib
  - export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH
  - mkdir -p $HOME/bin
  - export PATH=$HOME/bin:$PATH
  - mkdir -p $HOME/include
  - export CPLUS_INCLUDE_PATH=$HOME/include:$CPLUS_INCLUDE_PATH
  - cd sndwch/build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$HOME
  - make
  - make install
  - cd ../../
  - mkdir build
  - cd build
  - cmake ../src
  - make