language: c++
compiler: g++

os:
  - linux
  - osx
  
#sudo: required
#dist: trusty

addons:
  apt:
    packages:
      - build-essential
      - qt5-default
      - libqt5svg5-dev

before_install:
#  - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
#  - sudo apt-get update
  - git clone https://github.com/neonsoftware/sndwch.git
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt ; fi


#install:
#  - sudo apt-get install build-essential qt5-default libqt5svg5-dev
#  - sudo apt-cache search qt5svg-dev

script:

  - pwd 
#  - mkdir -p $HOME/lib
#  - export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH
#  - mkdir -p $HOME/bin
#  - export PATH=$HOME/bin:$PATH
#  - mkdir -p $HOME/include
#  - export CPLUS_INCLUDE_PATH=$HOME/include:$CPLUS_INCLUDE_PATH
  - cd sndwch/build
  - cmake ..
  - make
  - sudo make install
  - cd ../../
  - mkdir build
  - cd build
  - cmake ../src
  - make