language: c++
compiler: g++

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - build-essential
      - qt5-default
      - libqt5svg5-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link qt ; fi
  - git clone https://github.com/neonsoftware/sndwch.git

script:

  - pwd 
#  - mkdir -p $HOME/lib
#  - export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH
#  - mkdir -p $HOME/bin
#  - export PATH=$HOME/bin:$PATH
#  - mkdir -p $HOME/include
#  - export CPLUS_INCLUDE_PATH=$HOME/include:$CPLUS_INCLUDE_PATH
  - cd sndwch/build
  - cmake ..
  - make
  - sudo make install
  - cd ../../
  - mkdir build
  - cd build
  - cmake ../src
  - make