image: Visual Studio 2015

install:
  #- vcpkg install libxml2:x64-windows
  - git clone https://github.com/yaml/libyaml
  - cd libyaml && cmake . && cmake --build . --target install && cd ..
  - git clone https://github.com/neonsoftware/sndwch.git
  - cd sndwch && cmake . && cmake --build . --target install && cd ..
