image: Visual Studio 2015

install:
  - vcpkg install libxml2:x64-windows
  - git clone https://github.com/yaml/libyaml
  - cd libyaml && cmake -G "Visual Studio 14 2015 Win64"  -DBUILD_SHARED_LIBS=a . && cmake --build . --target install && cd ..
  - git clone https://github.com/neonsoftware/sndwch.git
  - cd sndwch 
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_MODULE_PATH="C:/Program Files/yaml/cmake" -DCMAKE_PREFIX_PATH="c:/tools/vcpkg/installed/x64-windows;C:/Program Files/yaml" . 
  - cmake --build . --target install && cd ..
  - mkdir build 
  - cd build && cmake -G "Visual Studio 14 2015 Win64" ../src
  - cmake --build . --target install && cd ..

