image: Visual Studio 2015

platform:
  - x64

configuration:
  - Debug 

install:
  #- vcpkg install libxml2:x64-windows
  - git clone https://github.com/yaml/libyaml
  - cd libyaml && cmake . && cmake --build . --target install
