image: Visual Studio 2015

install:
  - vcpkg install libxml2:x64-windows
  - git clone https://github.com/yaml/libyaml
  - cd libyaml && cmake . && cmake --build . --target install && cd ..
  - git clone https://github.com/neonsoftware/sndwch.git
  - cd sndwch && cmake -DCMAKE_PREFIX_PATH="C:\Program Files (x86)\yaml" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake . && cmake --build . --target install && cd ..
  #- cd sndwch && cmake -DCMAKE_MODULE_PATH="C:/Program Files (x86)/yaml/cmake" . && cmake --build . --target install && cd ..